name: flutter_boxez
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get_it: any  
  bloc: any
  flutter_bloc: any
  equatable: any
  parameterized_test: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
